// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Add(repoPath: string, paths: string[]): $CancellablePromise<$models.GitResult> {
    return $Call.ByID(931596068, repoPath, paths).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AddLocalRepository(repoPath: string): $CancellablePromise<$models.RepositoryOperationResult> {
    return $Call.ByID(257058707, repoPath).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Branch(repoPath: string, name: string): $CancellablePromise<$models.GitResult> {
    return $Call.ByID(424910197, repoPath, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Checkout(repoPath: string, target: string, create: boolean): $CancellablePromise<$models.GitResult> {
    return $Call.ByID(41166665, repoPath, target, create).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Clone(repoURL: string, destination: string): $CancellablePromise<$models.GitResult> {
    return $Call.ByID(3320935538, repoURL, destination).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Commit(repoPath: string, message: string): $CancellablePromise<$models.GitResult> {
    return $Call.ByID(471482348, repoPath, message).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CommitSelected(repoPath: string, paths: string[], message: string, description: string): $CancellablePromise<$models.GitResult> {
    return $Call.ByID(2403931813, repoPath, paths, message, description).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Fetch(repoPath: string): $CancellablePromise<$models.GitResult> {
    return $Call.ByID(3105763379, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetCurrentRepository(): $CancellablePromise<$models.RepositoryOperationResult> {
    return $Call.ByID(3171085068).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListChanges(repoPath: string): $CancellablePromise<$models.ChangeListResult> {
    return $Call.ByID(636254054, repoPath).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListRepositories(): $CancellablePromise<$models.RepositoryOperationResult> {
    return $Call.ByID(3938114317).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Pull(repoPath: string): $CancellablePromise<$models.GitResult> {
    return $Call.ByID(3924717390, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Push(repoPath: string): $CancellablePromise<$models.GitResult> {
    return $Call.ByID(4024544461, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SelectAndAddLocalRepository(): $CancellablePromise<$models.RepositoryOperationResult> {
    return $Call.ByID(811600020).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetCurrentRepository(repoPath: string): $CancellablePromise<$models.RepositoryOperationResult> {
    return $Call.ByID(3154529440, repoPath).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SmartSync(repoPath: string): $CancellablePromise<$models.SmartSyncResult> {
    return $Call.ByID(2683247193, repoPath).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Status(repoPath: string): $CancellablePromise<$models.GitResult> {
    return $Call.ByID(1385891039, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.GitResult.createFrom;
const $$createType1 = $models.RepositoryOperationResult.createFrom;
const $$createType2 = $models.ChangeListResult.createFrom;
const $$createType3 = $models.SmartSyncResult.createFrom;
