// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChangeListResult {
    "success": boolean;
    "error": string;
    "changes": GitChange[];

    /** Creates a new ChangeListResult instance. */
    constructor($$source: Partial<ChangeListResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangeListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ChangeListResult {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField2_0($$parsedSource["changes"]);
        }
        return new ChangeListResult($$parsedSource as Partial<ChangeListResult>);
    }
}

export class GitChange {
    "path": string;
    "originalPath": string;
    "indexStatus": string;
    "worktreeStatus": string;

    /** Creates a new GitChange instance. */
    constructor($$source: Partial<GitChange> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("originalPath" in $$source)) {
            this["originalPath"] = "";
        }
        if (!("indexStatus" in $$source)) {
            this["indexStatus"] = "";
        }
        if (!("worktreeStatus" in $$source)) {
            this["worktreeStatus"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitChange instance from a string or object.
     */
    static createFrom($$source: any = {}): GitChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitChange($$parsedSource as Partial<GitChange>);
    }
}

export class GitResult {
    "success": boolean;
    "output": string;
    "error": string;
    "exitCode": number;

    /** Creates a new GitResult instance. */
    constructor($$source: Partial<GitResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GitResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitResult($$parsedSource as Partial<GitResult>);
    }
}

export class RepositoryOperationResult {
    "success": boolean;
    "error": string;
    "repository": string;
    "repositories": string[];
    "current": string;
    "cancelled": boolean;

    /** Creates a new RepositoryOperationResult instance. */
    constructor($$source: Partial<RepositoryOperationResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("repositories" in $$source)) {
            this["repositories"] = [];
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepositoryOperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RepositoryOperationResult {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repositories" in $$parsedSource) {
            $$parsedSource["repositories"] = $$createField3_0($$parsedSource["repositories"]);
        }
        return new RepositoryOperationResult($$parsedSource as Partial<RepositoryOperationResult>);
    }
}

export class SmartSyncResult {
    "success": boolean;
    "output": string;
    "error": string;
    "exitCode": number;
    "action": string;

    /** Creates a new SmartSyncResult instance. */
    constructor($$source: Partial<SmartSyncResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmartSyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SmartSyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SmartSyncResult($$parsedSource as Partial<SmartSyncResult>);
    }
}

// Private type creation functions
const $$createType0 = GitChange.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
