// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2) {
  return window['go']['main']['App']['Add'](arg1, arg2);
}

export function AddLocalRepository(arg1) {
  return window['go']['main']['App']['AddLocalRepository'](arg1);
}

export function Branch(arg1, arg2) {
  return window['go']['main']['App']['Branch'](arg1, arg2);
}

export function Checkout(arg1, arg2, arg3) {
  return window['go']['main']['App']['Checkout'](arg1, arg2, arg3);
}

export function Clone(arg1, arg2) {
  return window['go']['main']['App']['Clone'](arg1, arg2);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['App']['Commit'](arg1, arg2);
}

export function CommitSelected(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CommitSelected'](arg1, arg2, arg3, arg4);
}

export function Fetch(arg1) {
  return window['go']['main']['App']['Fetch'](arg1);
}

export function GetCurrentRepository() {
  return window['go']['main']['App']['GetCurrentRepository']();
}

export function ListChanges(arg1) {
  return window['go']['main']['App']['ListChanges'](arg1);
}

export function ListRepositories() {
  return window['go']['main']['App']['ListRepositories']();
}

export function Pull(arg1) {
  return window['go']['main']['App']['Pull'](arg1);
}

export function Push(arg1) {
  return window['go']['main']['App']['Push'](arg1);
}

export function SelectAndAddLocalRepository() {
  return window['go']['main']['App']['SelectAndAddLocalRepository']();
}

export function SetCurrentRepository(arg1) {
  return window['go']['main']['App']['SetCurrentRepository'](arg1);
}

export function SmartSync(arg1) {
  return window['go']['main']['App']['SmartSync'](arg1);
}

export function Status(arg1) {
  return window['go']['main']['App']['Status'](arg1);
}
