// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Add(arg1:string,arg2:Array<string>):Promise<main.GitResult>;

export function AddLocalRepository(arg1:string):Promise<main.RepositoryOperationResult>;

export function Branch(arg1:string,arg2:string):Promise<main.GitResult>;

export function Checkout(arg1:string,arg2:string,arg3:boolean):Promise<main.GitResult>;

export function Clone(arg1:string,arg2:string):Promise<main.GitResult>;

export function Commit(arg1:string,arg2:string):Promise<main.GitResult>;

export function CommitSelected(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<main.GitResult>;

export function Fetch(arg1:string):Promise<main.GitResult>;

export function GetCurrentRepository():Promise<main.RepositoryOperationResult>;

export function ListChanges(arg1:string):Promise<main.ChangeListResult>;

export function ListRepositories():Promise<main.RepositoryOperationResult>;

export function Pull(arg1:string):Promise<main.GitResult>;

export function Push(arg1:string):Promise<main.GitResult>;

export function SelectAndAddLocalRepository():Promise<main.RepositoryOperationResult>;

export function SetCurrentRepository(arg1:string):Promise<main.RepositoryOperationResult>;

export function SmartSync(arg1:string):Promise<main.SmartSyncResult>;

export function Status(arg1:string):Promise<main.GitResult>;
